insert into rating (username, stars) values ('ldraper1', '59');
insert into rating (username, stars) values ('dreayd', '72');
insert into rating (username, stars) values ('kmalimoe2', '42');
insert into rating (username, stars) values ('mfrancillob', '34');
insert into rating (username, stars) values ('jfreezorc', '83');
insert into rating (username, stars) values ('mlongcake4', '92');
insert into rating (username, stars) values ('elabastida8', '64');
insert into rating (username, stars) values ('mvgorshkoff', '16');
insert into rating (username, stars) values ('tledura', '20');
insert into rating (username, stars) values ('itongs5', '52');
insert into rating (username, stars) values ('joubridge6', '44');
insert into rating (username, stars) values ('mjeal0', '95');
insert into rating (username, stars) values ('bnorthcliffe9', '77');
insert into rating (username, stars) values ('apettiward7', '10');
insert into rating (username, stars) values ('etenniswood3', '60');
insert into rating (username, stars) values ('Test Max', '75');
insert into rating (username, stars) values ('M', '99');