# name: Build Project
# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master
# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0

#       - uses: docker/setup-buildx-action@v2

#       # TODO build, publish to docker hub, deploy to k8s

#       - name: Build, publish
#         env:
#           DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
#           DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
#         run: |
#           docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
#           docker build --no-cache -t mvgorshkoff/gateway ./library_system/gateway/
#           docker push mvgorshkoff/gateway:latest
#           docker build --no-cache -t mvgorshkoff/ratingsystem ./library_system/rating_system/
#           docker push mvgorshkoff/ratingsystem:latest
#           docker build --no-cache -t mvgorshkoff/librarysystem ./library_system/library_system/
#           docker push mvgorshkoff/librarysystem:latest
#           docker build --no-cache -t mvgorshkoff/reservationsystem ./library_system/reservation_system/
#           docker push mvgorshkoff/reservationsystem:latest
#           docker build --no-cache -t mvgorshkoff/identityprovider ./library_system/identity_provider/
#           docker push mvgorshkoff/identityprovider:latest
#           docker build --no-cache -t mvgorshkoff/frontend ./library_system/frontend/
#           docker push mvgorshkoff/frontend:latest

#      - name: Build images
#        timeout-minutes: 10
#        run: docker compose build

#      - name: Run containers
#        timeout-minutes: 5
#        run: |
#          docker compose up -d
#          ./scripts/wait-script.sh
#        env:
#          WAIT_PORTS: 8080,8070,8060,8050

#      - name: GitHub auto grader mark
#        uses: Romanow/google-sheet-autograder-marker@v1.0
#        with:
#          google_token: ${{secrets.GOOGLE_API_KEY}}
#          sheet_id: ""
#          homework_number: 1
#          user_column: 'D'
#          column_offset: 'F'
#          mark: "'+"

#      - name: Stop containers
#        if: always()
#        continue-on-error: true
#        run: docker compose down -v