name: Build Project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build, publish to docker hub, deploy to k8s

      - name: Build, publish
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker build --no-cache -t mvgorshkoff/gateway ./library_system/gateway/
          docker push mvgorshkoff/gateway:latest
          docker build --no-cache -t mvgorshkoff/ratingsystem ./library_system/rating_system/
          docker push mvgorshkoff/ratingsystem:latest
          docker build --no-cache -t mvgorshkoff/librarysystem ./library_system/library_system/
          docker push mvgorshkoff/librarysystem:latest
          docker build --no-cache -t mvgorshkoff/reservationsystem ./library_system/reservation_system/
          docker push mvgorshkoff/reservationsystem:latest
          docker build --no-cache -t mvgorshkoff/identityprovider ./library_system/identity_provider/
          docker push mvgorshkoff/identityprovider:latest
          docker build --no-cache -t mvgorshkoff/frontend ./library_system/frontend/
          docker push mvgorshkoff/frontend:latest

      - name: Deploy
        timeout-minutes: 5
        env:
          SERVER: "${{secrets.OKTETO_SERVER}}"
          TOKEN: "${{secrets.OKTETO_TOKEN}}"
          CERTIFICATE: "${{secrets.OKTETO_CERTIFICATE}}"
        run: |
          kubectl config set-cluster lab4 --server=$SERVER
          kubectl config set-credentials dev --token=$TOKEN
          kubectl config set clusters.lab4.certificate-authority-data $CERTIFICATE
          kubectl config set-context prod --cluster=lab4 --user=dev --namespace=villainnumberone
          kubectl config use-context prod
          helm upgrade --install library ./kubernetes/library
          kubectl apply -f ./kubernetes/ingress.yaml